/* =============================================================
// dialogue.js
// -------------------------------------------------------------
// All the key dialogue used in the game, in English.
// ===========================================================*/

var keyList = [
	"It's just you here...",
	"Welcome back to the party!",
];

var rejectionList = [
	"I don't know you...",
	"I don't have a ride!",
	"My dog is throwing up.",
	"I have a package I have to sign for.",
	"I wish but Uber surge pricing is at 5.6x right now!",
	"It's raining, maybe another time.",
	"I had a burrito for dinner and now I can't move.",
	"My kid is sick, I gotta stay here.",
	"I have a migraine, party on without me.",
	"I can't find my keys.",
	"I'm too upset about the state of the country to party right now.",
	"i have terrible diarrhea.",
	"There's a flash flood warning in my area.",
	"I just really don't want to be hungover tomorrow.",
	"Didn't we already party last weekend...?",
	"I'm just not feeling it this week.",
	"I started FriendSpace beef so I'm trying to keep it low key.",
	"You know the exposed video? That was me. Probably best to lay low.",
	"Sorry, my nails are still drying.",
	"I'm dog sitting.",
	"I'm cat sitting.",
	"i found a baby on my doorstep and I have to raise it now.",
	"I don't feel like putting on pants.",
	"I'd rather be asleep.",
	"I'd Rather Be Dead",
	"My social anxiety is flaring up.",
	"I'm in the middle of a FriendSpace argument, party later?",
	"Sorry, I've got a doctor's appointment",
	"I'd love to... But I can't",
	"Sorry man, I got a thing...",
	"I'm actually late for class!",
	"Sorry! I'm stuck in an escape room rn"
];

var acceptanceList = [
	"It ain't a party until I'm here!",
	"Parties are like, kinda my thing.",
	"A party? I'm game.",
	"You know I'm always down for a party.",
	"I hope the beer is still cold!",
	"I'm there.",
	"Is it even a party without me there?",
	"Hope there's enough beer!"
];

var noRoomList = [
	"I can't squeeze in!",
	"Looks like there's no more room!",
	"I'd love to, but there's no room!",
	"Looks like your party is at max capacity",
	"No room for me."
];

var kickedOutList = [
	"You really gonna kick me out? Whack.",
	"You don't have to kick me out, 'cause I'm gone.",
	"See if I ever party with you again...",
	"Oh well, there's a better party I want to go to anyway.",
	"Thanks for clearing up my schedule, jerk.",
	"Really? Your party sucks anyway.",
	"Forget this party.",
	"I didn't even want to be here, anyway.",
	"Smell ya later.",
	"Peace!"
];

var genericTextMessages = [
	"Hey dude, what's up?",
	"We still on for tomorrow?",
	"Dude I heard you were throwing a party? What's up with that?",
	"hey man lets not talk about last night... we cool, right?",
	"we gotta chill sometime man hmu",
	"whats this talk about a party?",
	"omg did you see that light in the sky?",
	"yo is the power at your house getting weird?",
	"do you have that $20 you owe me?"
];

var genericWrongNumberMessages = [
	"Hey Kate, can you pick up the BBQ?",
	"Todavía no he olvidado el incidente.",
	"ainda precisamos ir às compras",
	"mike, please call me...its urgent",
	"hi this is barb i was just wondering if u wanted to come over for pizza, i hope this is the rite number",
	"hello?",
	"salom?",
	"Need some INSTANT-CA$H right now? Get up to $1000$--TODAY! Reply YES for further info, or NO for -UNSUBSCRIBE-",
	"HURRY UP!TODAY ONLY!RayBan&Oakley Sunglasses Outlets. ALL SALES 88% OFF! Shop Now",
	"New offer 39ffasi3asd0 show this for a $9 cut (exp. 10/23/99). Join our loyalty club & your 5th haircut is FREE! Reply STOP to opt out",
	"Due to a new legislation, those struggling with debt can now apply to have it written off. For FREE information reply INFO or to opt-out text stop.",
	"we kn0w y0u 4re 0uT tHEre",
	"y0u 4re tHe sEED anD Us tHE tRee",
	"kEEp PartYing",
	"thEre Is 0nLy 1 wAy...tO PARTY",
	"pArTy aLL nite aND dAy",
	"y0u cAn rEaCH uS...tHr0ugH pArTy"
];

var genericFriendSpacePosts = [
	"party time.",
	"who wants to party?",
	"i can't wait to party.",
	"I've been seeing a lot more stars in the sky lately.",
	"Do aliens exist?",
	"I want to believe",
	"always looking for the best parties...sometimes i find them, sometimes they find me.",
	"still searching...",
	"im still sick from that burrito last night, ugh.",
	"yo friends, anyone else feel sick after last nights pizza party? was there something in the wings?",
	"just had ate too much pizza... guess it was possible. oof.",
	"currently in the middle of an argument where i just realized i was wrong. gonna keep this going tho.",
	"I need a really good nap :(",
	"Pizza time!",
	"In need of a good hug. :/",
	"who does the emojis with the nose anymore? only weirdos... :-)",
	"just trying to get this bread (i love carbs)",
	"working on a new beat, gonna be fire, so stoked",
	"y'all hear that new yung ez joint?",
	"I heard someone was trying to throw the biggest party ever?",
	"wheres this epic party i keep hearing about? someone text me the addy",
	"ALL YOUR BASE ARE BELONG TO US",
	"I wonder if there's any cool parties happening.",
	"I haven't been the same since the accident.",
	"What are your favorite party songs?",
	"Did anyone else see that light in the sky?",
	"Where can I download free ringtones?",
	"Just had the craziest dream! You had to be there.",
	"I'm going to bed, you guys want anything?",
	"is broga a thing? yoga for bros?",
	"calling my friend group a cinematic universe from now on",
	"i say y'all way too much for someone who has been to the south once and it was just a layover",
	"love when soundcloud rappers with 27 followers write their bio as a 5 paragraph essay in the 3rd person",
	"damn i gotta go to more arab weddings",
	"y'all see that wall of death at the show last night?",
	"professor x: what's ur genetic mutation? me: cilantro tastes like soap",
	"beer is just alcoholic liquid bread",
	"things im leaving behind in 2018: fake people, one sided friendships, and that $200 i owe you derek stop texting me",
	"enchiladas are like mexican lasagna",
	"just stopped my mom from buying a 5lb bag of offbrand pre-shredded mozzarella cheese. i expect my nobel peace prize anytime now.",
	"Myers–Briggs personality types are the \"smart\" person's version of horoscopes.",
	"doing this new thing where i call hot water \"spicy water\" and its really been a hit tbh",
	"Geometry > Algebra > Pre-Calculus > Calculus > Figuring out what toilet paper gives you the best deal > Linear Algebra",
	"if my future wife ever calls me \"hubby\" im filing for divorce",
	"bloody marys are so nasty. like id rather stand in front of a bathroom mirror with the lights off and say bloody mary 3 times than drink a cup of that spoiled ragu",
	"unsubscribing from a youtube channel and then seeing their latest video on the home page is the same level of awkward as seeing your ex at the mall all moved on without you",
	"If my ears pop on my way to your place you're part of the 1%.",
	"this little kid waited until i wasn't looking to put sweet tea into a ketchup cup. don't worry, lil homie, i ain't no snitch.",
	"s/o to all the mom's who after any phone going off in a room ask \"is that my phone?\"",
	"\"and the oscar goes to.... vines that keep me from ending it all part 4!\"",
	"If your article has gifs embedded in it, it's no longer credible.",
	"\"bake for 10-12 minutes\"? 11 minutes, got it.",
	"hot chocolate made with water instead of milk is not hot chocolate that's just dirty water.",
	"just saw a guy at chipotle bite right into his burrito without unwrapping the foil then go into the parking lot and lift a car over his head wtf",
	"Millennials don't want avocado toast, they want to die.",
	"Rick Moranis just served me at Chick-fil-A and he nailed that air toss cup flip before filling up my drink.",
	"I don't understand people sneaking in pizza into a movie theater. The last thing I want to try to do in a dark theater is attempt to eat greasy pizza over my lap while everyone around me smells how much of a prick I am.",
	"Not deglazing a pan is a sin in God's eyes.",
	"the guy that came up with the game hide n seek probably had ulterior motives.",
	"s/o to all the old homies who were \"last seen online 8 years ago\".",
	"gas fire pits are dumb like might as well roast marshmallows on the stove",
	"ive never felt more objectified than that time my dentist used my chest as a table for his tools",
	"when white people talk about seasoning their food they mean garlic salt and lemon pepper.",
	"hate it when they say \"ill have the total for you at the 2nd window\". i need to know how much coins to scrape up from under my seat and my sticky cupholder to pay for this burrito",
	"the guy behind me in line at the bank was pacing back and forth, if i die, leak my mixtape",
	"my bank likes to send me an email once a week reminding me of how broke i am",
	"modern gaming went downhill since the exclusion of big head mode",
	"just did so bad on my midterm i went ahead marked myself down for the professor",
	"if i could have one superpower, it would be to always know the perfect tuberware for leftovers",
	"if ur bio includes how to pronounce ur band name then u need a new band name",
	"once you go rearview camera, you can't go back",
	"i like how the clerk at my college's student store calls me \"sir\" like bro we had stats last quarter its chill",
	"it's crazy these days u can have any career u want as long as u put it in ur bio",
	"i wish i was rich enough to match my shoes with any other part of my outfit on purpose",
	"whenever i enter an elevator i always stand furthest from the buttons cause thats just too much responsibility for me i get anxiety",
	"people be acting like they boujee with their himalayan pink salt, dijon mustard, and strong family support system",
	"when u say good night to ur girl early so u can enjoy netflix on ur phone in bed without interruptions",
	"soggy cereal doesn't deserve the hate.",
	"Every bumper sticker says \"I'm poor\".",
	"whipped cream cheese is just like regular cream cheese but his wife calls all the shots",
	"Scientists have recently discovered that all life isn't, in fact, made up of carbon, but actually carbs.",
	"Anyone who calls it \"the little boys room\" should get their laptop searched by the FBI.",
	"Using limewire to get limewire pro was the first time I ever felt like a hacker",
	"My favorite episode of Game of Thrones is S03E07.AMZN.WEBRip.DDP5.0.x264.XviD.mkv",
	"i hope all my old online friends are doing ok",
	"all you need to know about my physical health is that i just broke a sweat fixing a doorknob",
	"cereal with whole milk is legally a dessert",
	"chicken tenders and mac n cheese is a fantastic dinner option for any occasion.",
	"Eating American cheese is straight up disrespecting your body.",
	"If you step out of the shower, and you realize you forgot to wash out the conditioner, do you jump back in or just keep crusin?",
	"I just heard the sound of a can opening in the stall next to mine. What does he know that I don't?",
	"My college motto is: write down now, understand later.",
	"I mean, you got a 10% chance of getting the last number of pi correct.",
	"currently in a very lit 30 person party bus and i think id rather be in the backseat of my parents car while they fight in the front.",
	"shout out to all my friendships that started and ended with my college semester",
	"invite a girl over for movie night, suggest a doc u have to watch for ur class, ask her the discussion q's u have to answer, look deep af",
	"so many oreo flavors. so little time.",
	"ive had clothes in the dryer since like 2007",
	"putting band stickers on my reusable water bottle so people know not only do i care about the environment but my taste in music is great.",
	"camping is just pretend homelessness",
	"Currently eating my feelings. Tonight's feeling is hungry.",
	"you're born, then you take baths, then you take showers, then you take baths, then you die",
	"salads are just ranch delivery systems",
	"Now I'm not saying I'm better than you, but what I am saying is that I'm currently drinking a fresh homemade cucumber, mint, matcha lemonade",
	"I have two half brothers or as I more commonly say, one whole brother.",
	"unlimited breadsticks = unlimited power",
	"A tight plastic wrapped cane is easily the most inefficient candy delivery system.",
	"If anyone was thinking of getting me an early half birthday gift, I'm running low on scented candles.",
	"The lady in the elevator told me to have a good day. I was actually planning on having a bad day, so I guess I gotta change my schedule up.",
	"my mom calls every video game character \"mario\", every game console \"the nintendo\", and every one of her kids \"a disappointment\"",
	"what do the other 3 sides of the food pyramid look like?",
	"anyone need a new buddy to hang out with? asking for a friend.",
	"Only rich people know if they have a horse allergy.",
	"*plays air guitar* *breaks a string*",
	"Weekend goals: procrastinate on homework. No judge, just having realistic goals.",
	"Putting your money where your mouth is sounds like a germaphobe's worst nightmare.",
	"my favorite drink at the bar is whatever the bartender thinks I was trying to order",
	"lettuce wrapped burgers aint so bad, its like a handheld burger salad.",
	"Sad I've never been a part of a real football huddle.",
	"My depressive episode was picked up for a whole series!",
	"just had the best burrito ever. anyone else who had a burrito for dinner today, know that someone else had a better one.",
	"My friend once asked me what I get when I go to a bar. I told her anxiety.",
	"The most I've ever felt like an adult was talking about \"the budget\" at work last week.",
	"life begins when you discover dipping fries in ranch",
	"you dont know who your friends are until you know what meat & veggies they like in their breakfast burrito",
	"my signature dance move at the club is checking for texts when my phone hasn't buzzed in hours",
	"room for dessert? that's just a good idea",
	"kids these days are starting young, next thing you know they'll be snorting their flintstones vitamins because it 'kicks in faster fam'.",
	"cheesy breadsticks & marinara sauce? thats just an inefficient way 2 eat pizza. thats just a ploy by the pizza companies 2 sell u more pizza",
	"why dont we just make the whole table out of coasters ?",
	"I get all my pop culture news from standing in line at grocery stores.",
	"I never know where to park at car dealerships.",
	"Just pretended to be asleep and then actually fell asleep.",
	"Very disappointing when you take that last sip of tea and realize you forgot to stir in the sugar.",
	"If you think about it, every exit is an emergency exit under the right circumstances.",
	"I wear sunglasses, not to block the sun from my eyes, but actually just so I have something to yank off when something crazy happens."
];